# Generated by Django 4.1 on 2022-08-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('loand_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=11)),
                ('loan_date', models.CharField(max_length=10)),
                ('loan_total', models.DecimalField(decimal_places=2, max_digits=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
