# Generated by Django 4.1 on 2022-08-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcciones',
            old_name='calle',
            new_name='Calle',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='ciudad',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='numero',
            new_name='Numero',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='pais',
            new_name='Pais',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='provincia',
            new_name='Provincia',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='brach_adress',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='brach_number',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='branch_name',
            new_name='Numero',
        ),
    ]
