# Generated by Django 4.1 on 2022-08-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_rename_calle_direcciones_calle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direcciones',
            old_name='Calle',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='Ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='Numero',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='Pais',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='Provincia',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='Direccion',
            new_name='brach_adress',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='Nombre',
            new_name='brach_number',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='Numero',
            new_name='branch_name',
        ),
    ]
