# Generated by Django 4.1 on 2022-08-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_rename_calle_direcciones_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciones',
            name='idDirecciones',
        ),
    ]
