# Generated by Django 4.1 on 2022-08-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_surname', models.CharField(max_length=255)),
                ('employee_hire_date', models.CharField(max_length=10)),
                ('employee_DNI', models.CharField(max_length=9)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
                ('idDirecciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sujetodireccion')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('iban', models.CharField(max_length=255)),
                ('limiteExtraccionDiario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limiteTransferenciaRecibida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costoTransferenciaRecibida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saldoDescubiertoDisponible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipoCuenta', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
