# Generated by Django 4.1 on 2022-08-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marcaID', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('tipoTarjetaID', models.AutoField(primary_key=True, serialize=False)),
                ('tipoTarjeta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numeroTarjeta', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('CVV', models.CharField(max_length=3)),
                ('fechaOtorgamiento', models.CharField(max_length=10)),
                ('fechaExpiracion', models.CharField(max_length=10)),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('marcaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.marca')),
                ('tipoTarjetaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.tipotarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('movimientoID', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('tipoMovimiento', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=10)),
                ('account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta')),
            ],
        ),
    ]
