# Generated by Django 4.1 on 2022-08-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_surname', models.CharField(max_length=255)),
                ('customer_DNI', models.CharField(max_length=9)),
                ('dob', models.CharField(max_length=10)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
                ('direcciones_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sujetodireccion')),
            ],
        ),
    ]
