# Generated by Django 4.1 on 2022-08-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='customer_name',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='customer_DNI',
            new_name='DNI',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dob',
            new_name='Nacimiento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='customer_surname',
            new_name='Nombre',
        ),
    ]
