# Generated by Django 4.1 on 2022-08-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_customer_name_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='DNI',
            new_name='customer_DNI',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellido',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre',
            new_name='customer_surname',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nacimiento',
            new_name='dob',
        ),
    ]
